# Generated by Django 4.2.1 on 2023-05-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=12, unique=True, verbose_name='Numero Factura')),
                ('anio', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(max_length=18, verbose_name='Nombre del cliente')),
                ('cliente_direccion', models.CharField(max_length=120, verbose_name='Direccion cliente')),
            ],
            options={
                'verbose_name': 'Facturas',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=24, verbose_name='Nombre de producto')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio unitario')),
                ('unidades', models.IntegerField(verbose_name='Unidades')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='factura.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Linea factura',
                'verbose_name_plural': 'Lineas Facturas',
            },
        ),
    ]
